[package]
name = "uhd-rs"
version = "0.1.1"
edition = "2024"
rust-version = "1.88"
description = "Rust-native USRP B2xx RX driver built on nusb."
# License same as libuhd, because likely derivative work.
license = "GPL-3.0-or-later"
readme = "README.md"
documentation = "https://docs.rs/uhd-rs"
repository = "https://github.com/bastibl/uhd-rs"
keywords = ["usrp", "sdr", "usb", "nusb", "webusb"]
categories = ["hardware-support", "asynchronous"]
include = ["src/**", "examples/**", "tests/**", "images/**", "Cargo.toml", "Cargo.lock", "README.md", "LICENSE", ".cargo/config.toml"]

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = ["embedded-images"]
embedded-images = ["dep:rust-embed"]
smol = ["nusb/smol"]
tokio = ["nusb/tokio"]
hardware-tests = []
wasm = []

[dependencies]
futures-lite = "2.6"
futures-timer = { version = "3.0", features = ["wasm-bindgen"] }
nusb = "0.2.7"
num-complex = "0.4"
async-lock = "3.4"
web-time = "1.1"
rust-embed = { version = "8.12", optional = true, features = ["debug-embed", "compression", "deterministic-timestamps"] }
thiserror = "2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Navigator", "Usb", "UsbDevice"] }
wasm-bindgen-futures = "0.4"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"
